//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// Этот исходный код был создан с помощью wsdl, версия=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Web.Services.WebServiceBindingAttribute(Name="GetCarList_Binding", Namespace="urn:microsoft-dynamics-schemas/page/getcarlist")]
public interface IGetCarList_Binding {
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/getcarlist:Read", RequestNamespace="urn:microsoft-dynamics-schemas/page/getcarlist", ResponseElementName="Read_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/getcarlist", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("GetCarList")]
    GetCarList Read(string No);
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/getcarlist:ReadByRecId", RequestNamespace="urn:microsoft-dynamics-schemas/page/getcarlist", ResponseElementName="ReadByRecId_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/getcarlist", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("GetCarList")]
    GetCarList ReadByRecId(string recId);
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/getcarlist:ReadMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/getcarlist", ResponseElementName="ReadMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/getcarlist", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlArrayAttribute("ReadMultiple_Result")]
    [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    GetCarList[] ReadMultiple(GetCarList_Filter[] filter, string bookmarkKey, int setSize);
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/getcarlist:IsUpdated", RequestNamespace="urn:microsoft-dynamics-schemas/page/getcarlist", ResponseElementName="IsUpdated_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/getcarlist", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("IsUpdated_Result")]
    bool IsUpdated(string Key);
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/getcarlist:GetRecIdFromKey", RequestNamespace="urn:microsoft-dynamics-schemas/page/getcarlist", ResponseElementName="GetRecIdFromKey_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/getcarlist", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("GetRecIdFromKey_Result")]
    string GetRecIdFromKey(string Key);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/getcarlist")]
public partial class GetCarList {
    
    private string keyField;
    
    private string noField;
    
    private string descriptionField;
    
    private string inventory_NumberField;
    
    private string responsible_EmployeeField;
    
    private string fA_Location_CodeField;
    
    private string vehicle_Identification_NumberField;
    
    private string vehicle_ModelField;
    
    private string vehicle_Reg_NoField;
    
    /// <remarks/>
    public string Key {
        get {
            return this.keyField;
        }
        set {
            this.keyField = value;
        }
    }
    
    /// <remarks/>
    public string No {
        get {
            return this.noField;
        }
        set {
            this.noField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public string Inventory_Number {
        get {
            return this.inventory_NumberField;
        }
        set {
            this.inventory_NumberField = value;
        }
    }
    
    /// <remarks/>
    public string Responsible_Employee {
        get {
            return this.responsible_EmployeeField;
        }
        set {
            this.responsible_EmployeeField = value;
        }
    }
    
    /// <remarks/>
    public string FA_Location_Code {
        get {
            return this.fA_Location_CodeField;
        }
        set {
            this.fA_Location_CodeField = value;
        }
    }
    
    /// <remarks/>
    public string Vehicle_Identification_Number {
        get {
            return this.vehicle_Identification_NumberField;
        }
        set {
            this.vehicle_Identification_NumberField = value;
        }
    }
    
    /// <remarks/>
    public string Vehicle_Model {
        get {
            return this.vehicle_ModelField;
        }
        set {
            this.vehicle_ModelField = value;
        }
    }
    
    /// <remarks/>
    public string Vehicle_Reg_No {
        get {
            return this.vehicle_Reg_NoField;
        }
        set {
            this.vehicle_Reg_NoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/getcarlist")]
public partial class GetCarList_Filter {
    
    private GetCarList_Fields fieldField;
    
    private string criteriaField;
    
    /// <remarks/>
    public GetCarList_Fields Field {
        get {
            return this.fieldField;
        }
        set {
            this.fieldField = value;
        }
    }
    
    /// <remarks/>
    public string Criteria {
        get {
            return this.criteriaField;
        }
        set {
            this.criteriaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/getcarlist")]
public enum GetCarList_Fields {
    
    /// <remarks/>
    No,
    
    /// <remarks/>
    Description,
    
    /// <remarks/>
    Inventory_Number,
    
    /// <remarks/>
    Responsible_Employee,
    
    /// <remarks/>
    FA_Location_Code,
    
    /// <remarks/>
    Vehicle_Identification_Number,
    
    /// <remarks/>
    Vehicle_Model,
    
    /// <remarks/>
    Vehicle_Reg_No,
}
