//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// Этот исходный код был создан с помощью wsdl, версия=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Web.Services.WebServiceBindingAttribute(Name="SPIntegration_Binding", Namespace="urn:microsoft-dynamics-schemas/codeunit/SPIntegration")]
public interface ISPIntegration_Binding {
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/SPIntegration:CreateAdvanceStatementHeade" +
        "r", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/SPIntegration", ResponseElementName="CreateAdvanceStatementHeader_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/SPIntegration", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
    string CreateAdvanceStatementHeader(string employeeNo, string advancePurpose, string postingDescription, [System.Xml.Serialization.XmlElementAttribute(DataType="date")] System.DateTime postingDate, string purchaserCode);
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/SPIntegration:CreateAdvanceStatementLine", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/SPIntegration", ResponseElementName="CreateAdvanceStatementLine_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/SPIntegration", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
    int CreateAdvanceStatementLine(string advStNo, string gLAccountNo, string vendorPostingGroup, string descriptionTxt, decimal amountInclVAT, string purchDocNo, [System.Xml.Serialization.XmlElementAttribute(DataType="date")] System.DateTime purchDocDate);
}
