//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/page/getemployeeledgerentries", ConfigurationName="NavisionGetEmployeeLedgerEntriesServiceReference.GetEmployeeLedgerEntries_Port")]
    public interface GetEmployeeLedgerEntries_Port {
        
        // CODEGEN: Generating message contract since the wrapper name (Read_Result) of message Read_Result does not match the default value (Read)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/getemployeeledgerentries:Read", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.Read_Result Read(Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.Read request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/getemployeeledgerentries:Read", ReplyAction="*")]
        System.Threading.Tasks.Task<Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.Read_Result> ReadAsync(Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.Read request);
        
        // CODEGEN: Generating message contract since the wrapper name (ReadByRecId_Result) of message ReadByRecId_Result does not match the default value (ReadByRecId)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/getemployeeledgerentries:ReadByRecId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.ReadByRecId_Result ReadByRecId(Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.ReadByRecId request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/getemployeeledgerentries:ReadByRecId", ReplyAction="*")]
        System.Threading.Tasks.Task<Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.ReadByRecId_Result> ReadByRecIdAsync(Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.ReadByRecId request);
        
        // CODEGEN: Generating message contract since the wrapper name (ReadMultiple_Result) of message ReadMultiple_Result does not match the default value (ReadMultiple)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/getemployeeledgerentries:ReadMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.ReadMultiple_Result ReadMultiple(Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.ReadMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/getemployeeledgerentries:ReadMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.ReadMultiple_Result> ReadMultipleAsync(Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.ReadMultiple request);
        
        // CODEGEN: Generating message contract since the wrapper name (IsUpdated_Result) of message IsUpdated_Result does not match the default value (IsUpdated)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/getemployeeledgerentries:IsUpdated", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.IsUpdated_Result IsUpdated(Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.IsUpdated request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/getemployeeledgerentries:IsUpdated", ReplyAction="*")]
        System.Threading.Tasks.Task<Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.IsUpdated_Result> IsUpdatedAsync(Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.IsUpdated request);
        
        // CODEGEN: Generating message contract since the wrapper name (GetRecIdFromKey_Result) of message GetRecIdFromKey_Result does not match the default value (GetRecIdFromKey)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/getemployeeledgerentries:GetRecIdFromKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.GetRecIdFromKey_Result GetRecIdFromKey(Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.GetRecIdFromKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/getemployeeledgerentries:GetRecIdFromKey", ReplyAction="*")]
        System.Threading.Tasks.Task<Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.GetRecIdFromKey request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/getemployeeledgerentries")]
    public partial class GetEmployeeLedgerEntries : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private int entry_NoField;
        
        private bool entry_NoFieldSpecified;
        
        private System.DateTime posting_DateField;
        
        private bool posting_DateFieldSpecified;
        
        private string vleDescriptionField;
        
        private string vlePaymPurpField;
        
        private string vendor_NoField;
        
        private int vendor_Ledger_Entry_NoField;
        
        private bool vendor_Ledger_Entry_NoFieldSpecified;
        
        private string vendor_Posting_GroupField;
        
        private Entry_Type entry_TypeField;
        
        private bool entry_TypeFieldSpecified;
        
        private Document_Type document_TypeField;
        
        private bool document_TypeFieldSpecified;
        
        private string document_NoField;
        
        private decimal amount_LCYField;
        
        private bool amount_LCYFieldSpecified;
        
        private int applied_Vend_Ledger_Entry_NoField;
        
        private bool applied_Vend_Ledger_Entry_NoFieldSpecified;
        
        private bool unappliedField;
        
        private bool unappliedFieldSpecified;
        
        private int unapplied_by_Entry_NoField;
        
        private bool unapplied_by_Entry_NoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Entry_No {
            get {
                return this.entry_NoField;
            }
            set {
                this.entry_NoField = value;
                this.RaisePropertyChanged("Entry_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Entry_NoSpecified {
            get {
                return this.entry_NoFieldSpecified;
            }
            set {
                this.entry_NoFieldSpecified = value;
                this.RaisePropertyChanged("Entry_NoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=2)]
        public System.DateTime Posting_Date {
            get {
                return this.posting_DateField;
            }
            set {
                this.posting_DateField = value;
                this.RaisePropertyChanged("Posting_Date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Posting_DateSpecified {
            get {
                return this.posting_DateFieldSpecified;
            }
            set {
                this.posting_DateFieldSpecified = value;
                this.RaisePropertyChanged("Posting_DateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string vleDescription {
            get {
                return this.vleDescriptionField;
            }
            set {
                this.vleDescriptionField = value;
                this.RaisePropertyChanged("vleDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string vlePaymPurp {
            get {
                return this.vlePaymPurpField;
            }
            set {
                this.vlePaymPurpField = value;
                this.RaisePropertyChanged("vlePaymPurp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Vendor_No {
            get {
                return this.vendor_NoField;
            }
            set {
                this.vendor_NoField = value;
                this.RaisePropertyChanged("Vendor_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int Vendor_Ledger_Entry_No {
            get {
                return this.vendor_Ledger_Entry_NoField;
            }
            set {
                this.vendor_Ledger_Entry_NoField = value;
                this.RaisePropertyChanged("Vendor_Ledger_Entry_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Vendor_Ledger_Entry_NoSpecified {
            get {
                return this.vendor_Ledger_Entry_NoFieldSpecified;
            }
            set {
                this.vendor_Ledger_Entry_NoFieldSpecified = value;
                this.RaisePropertyChanged("Vendor_Ledger_Entry_NoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Vendor_Posting_Group {
            get {
                return this.vendor_Posting_GroupField;
            }
            set {
                this.vendor_Posting_GroupField = value;
                this.RaisePropertyChanged("Vendor_Posting_Group");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public Entry_Type Entry_Type {
            get {
                return this.entry_TypeField;
            }
            set {
                this.entry_TypeField = value;
                this.RaisePropertyChanged("Entry_Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Entry_TypeSpecified {
            get {
                return this.entry_TypeFieldSpecified;
            }
            set {
                this.entry_TypeFieldSpecified = value;
                this.RaisePropertyChanged("Entry_TypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public Document_Type Document_Type {
            get {
                return this.document_TypeField;
            }
            set {
                this.document_TypeField = value;
                this.RaisePropertyChanged("Document_Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Document_TypeSpecified {
            get {
                return this.document_TypeFieldSpecified;
            }
            set {
                this.document_TypeFieldSpecified = value;
                this.RaisePropertyChanged("Document_TypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Document_No {
            get {
                return this.document_NoField;
            }
            set {
                this.document_NoField = value;
                this.RaisePropertyChanged("Document_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public decimal Amount_LCY {
            get {
                return this.amount_LCYField;
            }
            set {
                this.amount_LCYField = value;
                this.RaisePropertyChanged("Amount_LCY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Amount_LCYSpecified {
            get {
                return this.amount_LCYFieldSpecified;
            }
            set {
                this.amount_LCYFieldSpecified = value;
                this.RaisePropertyChanged("Amount_LCYSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int Applied_Vend_Ledger_Entry_No {
            get {
                return this.applied_Vend_Ledger_Entry_NoField;
            }
            set {
                this.applied_Vend_Ledger_Entry_NoField = value;
                this.RaisePropertyChanged("Applied_Vend_Ledger_Entry_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Applied_Vend_Ledger_Entry_NoSpecified {
            get {
                return this.applied_Vend_Ledger_Entry_NoFieldSpecified;
            }
            set {
                this.applied_Vend_Ledger_Entry_NoFieldSpecified = value;
                this.RaisePropertyChanged("Applied_Vend_Ledger_Entry_NoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public bool Unapplied {
            get {
                return this.unappliedField;
            }
            set {
                this.unappliedField = value;
                this.RaisePropertyChanged("Unapplied");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UnappliedSpecified {
            get {
                return this.unappliedFieldSpecified;
            }
            set {
                this.unappliedFieldSpecified = value;
                this.RaisePropertyChanged("UnappliedSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public int Unapplied_by_Entry_No {
            get {
                return this.unapplied_by_Entry_NoField;
            }
            set {
                this.unapplied_by_Entry_NoField = value;
                this.RaisePropertyChanged("Unapplied_by_Entry_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Unapplied_by_Entry_NoSpecified {
            get {
                return this.unapplied_by_Entry_NoFieldSpecified;
            }
            set {
                this.unapplied_by_Entry_NoFieldSpecified = value;
                this.RaisePropertyChanged("Unapplied_by_Entry_NoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/getemployeeledgerentries")]
    public enum Entry_Type {
        
        /// <remarks/>
        Initial_Entry,
        
        /// <remarks/>
        Application,
        
        /// <remarks/>
        Unrealized_Loss,
        
        /// <remarks/>
        Unrealized_Gain,
        
        /// <remarks/>
        Realized_Loss,
        
        /// <remarks/>
        Realized_Gain,
        
        /// <remarks/>
        Payment_Discount,
        
        /// <remarks/>
        Payment_Discount_VAT_Excl,
        
        /// <remarks/>
        Payment_Discount_VAT_Adjustment,
        
        /// <remarks/>
        Appln_Rounding,
        
        /// <remarks/>
        Correction_of_Remaining_Amount,
        
        /// <remarks/>
        Payment_Tolerance,
        
        /// <remarks/>
        Payment_Discount_Tolerance,
        
        /// <remarks/>
        Payment_Tolerance_VAT_Excl,
        
        /// <remarks/>
        Payment_Tolerance_VAT_Adjustment,
        
        /// <remarks/>
        Payment_Discount_Tolerance_VAT_Excl,
        
        /// <remarks/>
        Payment_Discount_Tolerance_VAT_Adjustment,
        
        /// <remarks/>
        US_GAAP_Unrealized_Loss,
        
        /// <remarks/>
        US_GAAP_Unrealized_Gain,
        
        /// <remarks/>
        US_GAAP_Realized_Loss,
        
        /// <remarks/>
        US_GAAP_Realized_Gain,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/getemployeeledgerentries")]
    public enum Document_Type {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        Payment,
        
        /// <remarks/>
        Invoice,
        
        /// <remarks/>
        Credit_Memo,
        
        /// <remarks/>
        Finance_Charge_Memo,
        
        /// <remarks/>
        Reminder,
        
        /// <remarks/>
        Refund,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/getemployeeledgerentries")]
    public partial class GetEmployeeLedgerEntries_Filter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private GetEmployeeLedgerEntries_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public GetEmployeeLedgerEntries_Fields Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
                this.RaisePropertyChanged("Field");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
                this.RaisePropertyChanged("Criteria");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/getemployeeledgerentries")]
    public enum GetEmployeeLedgerEntries_Fields {
        
        /// <remarks/>
        Entry_No,
        
        /// <remarks/>
        Posting_Date,
        
        /// <remarks/>
        vleDescription,
        
        /// <remarks/>
        vlePaymPurp,
        
        /// <remarks/>
        Vendor_No,
        
        /// <remarks/>
        Vendor_Ledger_Entry_No,
        
        /// <remarks/>
        Vendor_Posting_Group,
        
        /// <remarks/>
        Entry_Type,
        
        /// <remarks/>
        Document_Type,
        
        /// <remarks/>
        Document_No,
        
        /// <remarks/>
        Amount_LCY,
        
        /// <remarks/>
        Applied_Vend_Ledger_Entry_No,
        
        /// <remarks/>
        Unapplied,
        
        /// <remarks/>
        Unapplied_by_Entry_No,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read", WrapperNamespace="urn:microsoft-dynamics-schemas/page/getemployeeledgerentries", IsWrapped=true)]
    public partial class Read {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/getemployeeledgerentries", Order=0)]
        public int Entry_No;
        
        public Read() {
        }
        
        public Read(int Entry_No) {
            this.Entry_No = Entry_No;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/getemployeeledgerentries", IsWrapped=true)]
    public partial class Read_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/getemployeeledgerentries", Order=0)]
        public Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.GetEmployeeLedgerEntries GetEmployeeLedgerEntries;
        
        public Read_Result() {
        }
        
        public Read_Result(Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.GetEmployeeLedgerEntries GetEmployeeLedgerEntries) {
            this.GetEmployeeLedgerEntries = GetEmployeeLedgerEntries;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId", WrapperNamespace="urn:microsoft-dynamics-schemas/page/getemployeeledgerentries", IsWrapped=true)]
    public partial class ReadByRecId {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/getemployeeledgerentries", Order=0)]
        public string recId;
        
        public ReadByRecId() {
        }
        
        public ReadByRecId(string recId) {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/getemployeeledgerentries", IsWrapped=true)]
    public partial class ReadByRecId_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/getemployeeledgerentries", Order=0)]
        public Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.GetEmployeeLedgerEntries GetEmployeeLedgerEntries;
        
        public ReadByRecId_Result() {
        }
        
        public ReadByRecId_Result(Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.GetEmployeeLedgerEntries GetEmployeeLedgerEntries) {
            this.GetEmployeeLedgerEntries = GetEmployeeLedgerEntries;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/getemployeeledgerentries", IsWrapped=true)]
    public partial class ReadMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/getemployeeledgerentries", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("filter")]
        public Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.GetEmployeeLedgerEntries_Filter[] filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/getemployeeledgerentries", Order=1)]
        public string bookmarkKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/getemployeeledgerentries", Order=2)]
        public int setSize;
        
        public ReadMultiple() {
        }
        
        public ReadMultiple(Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.GetEmployeeLedgerEntries_Filter[] filter, string bookmarkKey, int setSize) {
            this.filter = filter;
            this.bookmarkKey = bookmarkKey;
            this.setSize = setSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/getemployeeledgerentries", IsWrapped=true)]
    public partial class ReadMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadMultiple_Result", Namespace="urn:microsoft-dynamics-schemas/page/getemployeeledgerentries", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.GetEmployeeLedgerEntries[] ReadMultiple_Result1;
        
        public ReadMultiple_Result() {
        }
        
        public ReadMultiple_Result(Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.GetEmployeeLedgerEntries[] ReadMultiple_Result1) {
            this.ReadMultiple_Result1 = ReadMultiple_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated", WrapperNamespace="urn:microsoft-dynamics-schemas/page/getemployeeledgerentries", IsWrapped=true)]
    public partial class IsUpdated {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/getemployeeledgerentries", Order=0)]
        public string Key;
        
        public IsUpdated() {
        }
        
        public IsUpdated(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/getemployeeledgerentries", IsWrapped=true)]
    public partial class IsUpdated_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUpdated_Result", Namespace="urn:microsoft-dynamics-schemas/page/getemployeeledgerentries", Order=0)]
        public bool IsUpdated_Result1;
        
        public IsUpdated_Result() {
        }
        
        public IsUpdated_Result(bool IsUpdated_Result1) {
            this.IsUpdated_Result1 = IsUpdated_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey", WrapperNamespace="urn:microsoft-dynamics-schemas/page/getemployeeledgerentries", IsWrapped=true)]
    public partial class GetRecIdFromKey {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/getemployeeledgerentries", Order=0)]
        public string Key;
        
        public GetRecIdFromKey() {
        }
        
        public GetRecIdFromKey(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/getemployeeledgerentries", IsWrapped=true)]
    public partial class GetRecIdFromKey_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecIdFromKey_Result", Namespace="urn:microsoft-dynamics-schemas/page/getemployeeledgerentries", Order=0)]
        public string GetRecIdFromKey_Result1;
        
        public GetRecIdFromKey_Result() {
        }
        
        public GetRecIdFromKey_Result(string GetRecIdFromKey_Result1) {
            this.GetRecIdFromKey_Result1 = GetRecIdFromKey_Result1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GetEmployeeLedgerEntries_PortChannel : Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.GetEmployeeLedgerEntries_Port, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetEmployeeLedgerEntries_PortClient : System.ServiceModel.ClientBase<Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.GetEmployeeLedgerEntries_Port>, Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.GetEmployeeLedgerEntries_Port {
        
        public GetEmployeeLedgerEntries_PortClient() {
        }
        
        public GetEmployeeLedgerEntries_PortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetEmployeeLedgerEntries_PortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetEmployeeLedgerEntries_PortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetEmployeeLedgerEntries_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.Read_Result Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.GetEmployeeLedgerEntries_Port.Read(Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.Read request) {
            return base.Channel.Read(request);
        }
        
        public Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.GetEmployeeLedgerEntries Read(int Entry_No) {
            Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.Read inValue = new Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.Read();
            inValue.Entry_No = Entry_No;
            Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.Read_Result retVal = ((Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.GetEmployeeLedgerEntries_Port)(this)).Read(inValue);
            return retVal.GetEmployeeLedgerEntries;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.Read_Result> Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.GetEmployeeLedgerEntries_Port.ReadAsync(Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.Read request) {
            return base.Channel.ReadAsync(request);
        }
        
        public System.Threading.Tasks.Task<Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.Read_Result> ReadAsync(int Entry_No) {
            Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.Read inValue = new Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.Read();
            inValue.Entry_No = Entry_No;
            return ((Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.GetEmployeeLedgerEntries_Port)(this)).ReadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.ReadByRecId_Result Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.GetEmployeeLedgerEntries_Port.ReadByRecId(Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.ReadByRecId request) {
            return base.Channel.ReadByRecId(request);
        }
        
        public Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.GetEmployeeLedgerEntries ReadByRecId(string recId) {
            Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.ReadByRecId inValue = new Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.ReadByRecId();
            inValue.recId = recId;
            Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.ReadByRecId_Result retVal = ((Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.GetEmployeeLedgerEntries_Port)(this)).ReadByRecId(inValue);
            return retVal.GetEmployeeLedgerEntries;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.ReadByRecId_Result> Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.GetEmployeeLedgerEntries_Port.ReadByRecIdAsync(Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.ReadByRecId request) {
            return base.Channel.ReadByRecIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.ReadByRecId_Result> ReadByRecIdAsync(string recId) {
            Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.ReadByRecId inValue = new Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.ReadByRecId();
            inValue.recId = recId;
            return ((Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.GetEmployeeLedgerEntries_Port)(this)).ReadByRecIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.ReadMultiple_Result Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.GetEmployeeLedgerEntries_Port.ReadMultiple(Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.ReadMultiple request) {
            return base.Channel.ReadMultiple(request);
        }
        
        public Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.GetEmployeeLedgerEntries[] ReadMultiple(Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.GetEmployeeLedgerEntries_Filter[] filter, string bookmarkKey, int setSize) {
            Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.ReadMultiple inValue = new Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.ReadMultiple_Result retVal = ((Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.GetEmployeeLedgerEntries_Port)(this)).ReadMultiple(inValue);
            return retVal.ReadMultiple_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.ReadMultiple_Result> Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.GetEmployeeLedgerEntries_Port.ReadMultipleAsync(Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.ReadMultiple request) {
            return base.Channel.ReadMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.ReadMultiple_Result> ReadMultipleAsync(Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.GetEmployeeLedgerEntries_Filter[] filter, string bookmarkKey, int setSize) {
            Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.ReadMultiple inValue = new Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            return ((Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.GetEmployeeLedgerEntries_Port)(this)).ReadMultipleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.IsUpdated_Result Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.GetEmployeeLedgerEntries_Port.IsUpdated(Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.IsUpdated request) {
            return base.Channel.IsUpdated(request);
        }
        
        public bool IsUpdated(string Key) {
            Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.IsUpdated inValue = new Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.IsUpdated();
            inValue.Key = Key;
            Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.IsUpdated_Result retVal = ((Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.GetEmployeeLedgerEntries_Port)(this)).IsUpdated(inValue);
            return retVal.IsUpdated_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.IsUpdated_Result> Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.GetEmployeeLedgerEntries_Port.IsUpdatedAsync(Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.IsUpdated request) {
            return base.Channel.IsUpdatedAsync(request);
        }
        
        public System.Threading.Tasks.Task<Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.IsUpdated_Result> IsUpdatedAsync(string Key) {
            Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.IsUpdated inValue = new Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.IsUpdated();
            inValue.Key = Key;
            return ((Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.GetEmployeeLedgerEntries_Port)(this)).IsUpdatedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.GetRecIdFromKey_Result Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.GetEmployeeLedgerEntries_Port.GetRecIdFromKey(Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.GetRecIdFromKey request) {
            return base.Channel.GetRecIdFromKey(request);
        }
        
        public string GetRecIdFromKey(string Key) {
            Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.GetRecIdFromKey inValue = new Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.GetRecIdFromKey();
            inValue.Key = Key;
            Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.GetRecIdFromKey_Result retVal = ((Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.GetEmployeeLedgerEntries_Port)(this)).GetRecIdFromKey(inValue);
            return retVal.GetRecIdFromKey_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.GetRecIdFromKey_Result> Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.GetEmployeeLedgerEntries_Port.GetRecIdFromKeyAsync(Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.GetRecIdFromKey request) {
            return base.Channel.GetRecIdFromKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(string Key) {
            Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.GetRecIdFromKey inValue = new Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.GetRecIdFromKey();
            inValue.Key = Key;
            return ((Valeant.Sp.UprsWeb.NavisionGetEmployeeLedgerEntriesServiceReference.GetEmployeeLedgerEntries_Port)(this)).GetRecIdFromKeyAsync(inValue);
        }
    }
}
