//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valeant.Sp.UprsWeb.NavisionCarListServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/page/getcarlist", ConfigurationName="NavisionCarListServiceReference.GetCarList_Port")]
    public interface GetCarList_Port {
        
        // CODEGEN: Generating message contract since the wrapper name (Read_Result) of message Read_Result does not match the default value (Read)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/getcarlist:Read", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Valeant.Sp.UprsWeb.NavisionCarListServiceReference.Read_Result Read(Valeant.Sp.UprsWeb.NavisionCarListServiceReference.Read request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/getcarlist:Read", ReplyAction="*")]
        System.Threading.Tasks.Task<Valeant.Sp.UprsWeb.NavisionCarListServiceReference.Read_Result> ReadAsync(Valeant.Sp.UprsWeb.NavisionCarListServiceReference.Read request);
        
        // CODEGEN: Generating message contract since the wrapper name (ReadByRecId_Result) of message ReadByRecId_Result does not match the default value (ReadByRecId)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/getcarlist:ReadByRecId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Valeant.Sp.UprsWeb.NavisionCarListServiceReference.ReadByRecId_Result ReadByRecId(Valeant.Sp.UprsWeb.NavisionCarListServiceReference.ReadByRecId request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/getcarlist:ReadByRecId", ReplyAction="*")]
        System.Threading.Tasks.Task<Valeant.Sp.UprsWeb.NavisionCarListServiceReference.ReadByRecId_Result> ReadByRecIdAsync(Valeant.Sp.UprsWeb.NavisionCarListServiceReference.ReadByRecId request);
        
        // CODEGEN: Generating message contract since the wrapper name (ReadMultiple_Result) of message ReadMultiple_Result does not match the default value (ReadMultiple)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/getcarlist:ReadMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Valeant.Sp.UprsWeb.NavisionCarListServiceReference.ReadMultiple_Result ReadMultiple(Valeant.Sp.UprsWeb.NavisionCarListServiceReference.ReadMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/getcarlist:ReadMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<Valeant.Sp.UprsWeb.NavisionCarListServiceReference.ReadMultiple_Result> ReadMultipleAsync(Valeant.Sp.UprsWeb.NavisionCarListServiceReference.ReadMultiple request);
        
        // CODEGEN: Generating message contract since the wrapper name (IsUpdated_Result) of message IsUpdated_Result does not match the default value (IsUpdated)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/getcarlist:IsUpdated", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Valeant.Sp.UprsWeb.NavisionCarListServiceReference.IsUpdated_Result IsUpdated(Valeant.Sp.UprsWeb.NavisionCarListServiceReference.IsUpdated request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/getcarlist:IsUpdated", ReplyAction="*")]
        System.Threading.Tasks.Task<Valeant.Sp.UprsWeb.NavisionCarListServiceReference.IsUpdated_Result> IsUpdatedAsync(Valeant.Sp.UprsWeb.NavisionCarListServiceReference.IsUpdated request);
        
        // CODEGEN: Generating message contract since the wrapper name (GetRecIdFromKey_Result) of message GetRecIdFromKey_Result does not match the default value (GetRecIdFromKey)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/getcarlist:GetRecIdFromKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Valeant.Sp.UprsWeb.NavisionCarListServiceReference.GetRecIdFromKey_Result GetRecIdFromKey(Valeant.Sp.UprsWeb.NavisionCarListServiceReference.GetRecIdFromKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/getcarlist:GetRecIdFromKey", ReplyAction="*")]
        System.Threading.Tasks.Task<Valeant.Sp.UprsWeb.NavisionCarListServiceReference.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(Valeant.Sp.UprsWeb.NavisionCarListServiceReference.GetRecIdFromKey request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/getcarlist")]
    public partial class GetCarList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string noField;
        
        private string descriptionField;
        
        private string inventory_NumberField;
        
        private string responsible_EmployeeField;
        
        private string fA_Location_CodeField;
        
        private string vehicle_Identification_NumberField;
        
        private string vehicle_ModelField;
        
        private string vehicle_Reg_NoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string No {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
                this.RaisePropertyChanged("No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Inventory_Number {
            get {
                return this.inventory_NumberField;
            }
            set {
                this.inventory_NumberField = value;
                this.RaisePropertyChanged("Inventory_Number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Responsible_Employee {
            get {
                return this.responsible_EmployeeField;
            }
            set {
                this.responsible_EmployeeField = value;
                this.RaisePropertyChanged("Responsible_Employee");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string FA_Location_Code {
            get {
                return this.fA_Location_CodeField;
            }
            set {
                this.fA_Location_CodeField = value;
                this.RaisePropertyChanged("FA_Location_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Vehicle_Identification_Number {
            get {
                return this.vehicle_Identification_NumberField;
            }
            set {
                this.vehicle_Identification_NumberField = value;
                this.RaisePropertyChanged("Vehicle_Identification_Number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Vehicle_Model {
            get {
                return this.vehicle_ModelField;
            }
            set {
                this.vehicle_ModelField = value;
                this.RaisePropertyChanged("Vehicle_Model");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Vehicle_Reg_No {
            get {
                return this.vehicle_Reg_NoField;
            }
            set {
                this.vehicle_Reg_NoField = value;
                this.RaisePropertyChanged("Vehicle_Reg_No");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/getcarlist")]
    public partial class GetCarList_Filter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private GetCarList_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public GetCarList_Fields Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
                this.RaisePropertyChanged("Field");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
                this.RaisePropertyChanged("Criteria");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/getcarlist")]
    public enum GetCarList_Fields {
        
        /// <remarks/>
        No,
        
        /// <remarks/>
        Description,
        
        /// <remarks/>
        Inventory_Number,
        
        /// <remarks/>
        Responsible_Employee,
        
        /// <remarks/>
        FA_Location_Code,
        
        /// <remarks/>
        Vehicle_Identification_Number,
        
        /// <remarks/>
        Vehicle_Model,
        
        /// <remarks/>
        Vehicle_Reg_No,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read", WrapperNamespace="urn:microsoft-dynamics-schemas/page/getcarlist", IsWrapped=true)]
    public partial class Read {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/getcarlist", Order=0)]
        public string No;
        
        public Read() {
        }
        
        public Read(string No) {
            this.No = No;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/getcarlist", IsWrapped=true)]
    public partial class Read_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/getcarlist", Order=0)]
        public Valeant.Sp.UprsWeb.NavisionCarListServiceReference.GetCarList GetCarList;
        
        public Read_Result() {
        }
        
        public Read_Result(Valeant.Sp.UprsWeb.NavisionCarListServiceReference.GetCarList GetCarList) {
            this.GetCarList = GetCarList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId", WrapperNamespace="urn:microsoft-dynamics-schemas/page/getcarlist", IsWrapped=true)]
    public partial class ReadByRecId {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/getcarlist", Order=0)]
        public string recId;
        
        public ReadByRecId() {
        }
        
        public ReadByRecId(string recId) {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/getcarlist", IsWrapped=true)]
    public partial class ReadByRecId_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/getcarlist", Order=0)]
        public Valeant.Sp.UprsWeb.NavisionCarListServiceReference.GetCarList GetCarList;
        
        public ReadByRecId_Result() {
        }
        
        public ReadByRecId_Result(Valeant.Sp.UprsWeb.NavisionCarListServiceReference.GetCarList GetCarList) {
            this.GetCarList = GetCarList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/getcarlist", IsWrapped=true)]
    public partial class ReadMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/getcarlist", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("filter")]
        public Valeant.Sp.UprsWeb.NavisionCarListServiceReference.GetCarList_Filter[] filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/getcarlist", Order=1)]
        public string bookmarkKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/getcarlist", Order=2)]
        public int setSize;
        
        public ReadMultiple() {
        }
        
        public ReadMultiple(Valeant.Sp.UprsWeb.NavisionCarListServiceReference.GetCarList_Filter[] filter, string bookmarkKey, int setSize) {
            this.filter = filter;
            this.bookmarkKey = bookmarkKey;
            this.setSize = setSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/getcarlist", IsWrapped=true)]
    public partial class ReadMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadMultiple_Result", Namespace="urn:microsoft-dynamics-schemas/page/getcarlist", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Valeant.Sp.UprsWeb.NavisionCarListServiceReference.GetCarList[] ReadMultiple_Result1;
        
        public ReadMultiple_Result() {
        }
        
        public ReadMultiple_Result(Valeant.Sp.UprsWeb.NavisionCarListServiceReference.GetCarList[] ReadMultiple_Result1) {
            this.ReadMultiple_Result1 = ReadMultiple_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated", WrapperNamespace="urn:microsoft-dynamics-schemas/page/getcarlist", IsWrapped=true)]
    public partial class IsUpdated {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/getcarlist", Order=0)]
        public string Key;
        
        public IsUpdated() {
        }
        
        public IsUpdated(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/getcarlist", IsWrapped=true)]
    public partial class IsUpdated_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUpdated_Result", Namespace="urn:microsoft-dynamics-schemas/page/getcarlist", Order=0)]
        public bool IsUpdated_Result1;
        
        public IsUpdated_Result() {
        }
        
        public IsUpdated_Result(bool IsUpdated_Result1) {
            this.IsUpdated_Result1 = IsUpdated_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey", WrapperNamespace="urn:microsoft-dynamics-schemas/page/getcarlist", IsWrapped=true)]
    public partial class GetRecIdFromKey {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/getcarlist", Order=0)]
        public string Key;
        
        public GetRecIdFromKey() {
        }
        
        public GetRecIdFromKey(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/getcarlist", IsWrapped=true)]
    public partial class GetRecIdFromKey_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecIdFromKey_Result", Namespace="urn:microsoft-dynamics-schemas/page/getcarlist", Order=0)]
        public string GetRecIdFromKey_Result1;
        
        public GetRecIdFromKey_Result() {
        }
        
        public GetRecIdFromKey_Result(string GetRecIdFromKey_Result1) {
            this.GetRecIdFromKey_Result1 = GetRecIdFromKey_Result1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GetCarList_PortChannel : Valeant.Sp.UprsWeb.NavisionCarListServiceReference.GetCarList_Port, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetCarList_PortClient : System.ServiceModel.ClientBase<Valeant.Sp.UprsWeb.NavisionCarListServiceReference.GetCarList_Port>, Valeant.Sp.UprsWeb.NavisionCarListServiceReference.GetCarList_Port {
        
        public GetCarList_PortClient() {
        }
        
        public GetCarList_PortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetCarList_PortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetCarList_PortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetCarList_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Valeant.Sp.UprsWeb.NavisionCarListServiceReference.Read_Result Valeant.Sp.UprsWeb.NavisionCarListServiceReference.GetCarList_Port.Read(Valeant.Sp.UprsWeb.NavisionCarListServiceReference.Read request) {
            return base.Channel.Read(request);
        }
        
        public Valeant.Sp.UprsWeb.NavisionCarListServiceReference.GetCarList Read(string No) {
            Valeant.Sp.UprsWeb.NavisionCarListServiceReference.Read inValue = new Valeant.Sp.UprsWeb.NavisionCarListServiceReference.Read();
            inValue.No = No;
            Valeant.Sp.UprsWeb.NavisionCarListServiceReference.Read_Result retVal = ((Valeant.Sp.UprsWeb.NavisionCarListServiceReference.GetCarList_Port)(this)).Read(inValue);
            return retVal.GetCarList;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Valeant.Sp.UprsWeb.NavisionCarListServiceReference.Read_Result> Valeant.Sp.UprsWeb.NavisionCarListServiceReference.GetCarList_Port.ReadAsync(Valeant.Sp.UprsWeb.NavisionCarListServiceReference.Read request) {
            return base.Channel.ReadAsync(request);
        }
        
        public System.Threading.Tasks.Task<Valeant.Sp.UprsWeb.NavisionCarListServiceReference.Read_Result> ReadAsync(string No) {
            Valeant.Sp.UprsWeb.NavisionCarListServiceReference.Read inValue = new Valeant.Sp.UprsWeb.NavisionCarListServiceReference.Read();
            inValue.No = No;
            return ((Valeant.Sp.UprsWeb.NavisionCarListServiceReference.GetCarList_Port)(this)).ReadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Valeant.Sp.UprsWeb.NavisionCarListServiceReference.ReadByRecId_Result Valeant.Sp.UprsWeb.NavisionCarListServiceReference.GetCarList_Port.ReadByRecId(Valeant.Sp.UprsWeb.NavisionCarListServiceReference.ReadByRecId request) {
            return base.Channel.ReadByRecId(request);
        }
        
        public Valeant.Sp.UprsWeb.NavisionCarListServiceReference.GetCarList ReadByRecId(string recId) {
            Valeant.Sp.UprsWeb.NavisionCarListServiceReference.ReadByRecId inValue = new Valeant.Sp.UprsWeb.NavisionCarListServiceReference.ReadByRecId();
            inValue.recId = recId;
            Valeant.Sp.UprsWeb.NavisionCarListServiceReference.ReadByRecId_Result retVal = ((Valeant.Sp.UprsWeb.NavisionCarListServiceReference.GetCarList_Port)(this)).ReadByRecId(inValue);
            return retVal.GetCarList;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Valeant.Sp.UprsWeb.NavisionCarListServiceReference.ReadByRecId_Result> Valeant.Sp.UprsWeb.NavisionCarListServiceReference.GetCarList_Port.ReadByRecIdAsync(Valeant.Sp.UprsWeb.NavisionCarListServiceReference.ReadByRecId request) {
            return base.Channel.ReadByRecIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Valeant.Sp.UprsWeb.NavisionCarListServiceReference.ReadByRecId_Result> ReadByRecIdAsync(string recId) {
            Valeant.Sp.UprsWeb.NavisionCarListServiceReference.ReadByRecId inValue = new Valeant.Sp.UprsWeb.NavisionCarListServiceReference.ReadByRecId();
            inValue.recId = recId;
            return ((Valeant.Sp.UprsWeb.NavisionCarListServiceReference.GetCarList_Port)(this)).ReadByRecIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Valeant.Sp.UprsWeb.NavisionCarListServiceReference.ReadMultiple_Result Valeant.Sp.UprsWeb.NavisionCarListServiceReference.GetCarList_Port.ReadMultiple(Valeant.Sp.UprsWeb.NavisionCarListServiceReference.ReadMultiple request) {
            return base.Channel.ReadMultiple(request);
        }
        
        public Valeant.Sp.UprsWeb.NavisionCarListServiceReference.GetCarList[] ReadMultiple(Valeant.Sp.UprsWeb.NavisionCarListServiceReference.GetCarList_Filter[] filter, string bookmarkKey, int setSize) {
            Valeant.Sp.UprsWeb.NavisionCarListServiceReference.ReadMultiple inValue = new Valeant.Sp.UprsWeb.NavisionCarListServiceReference.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            Valeant.Sp.UprsWeb.NavisionCarListServiceReference.ReadMultiple_Result retVal = ((Valeant.Sp.UprsWeb.NavisionCarListServiceReference.GetCarList_Port)(this)).ReadMultiple(inValue);
            return retVal.ReadMultiple_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Valeant.Sp.UprsWeb.NavisionCarListServiceReference.ReadMultiple_Result> Valeant.Sp.UprsWeb.NavisionCarListServiceReference.GetCarList_Port.ReadMultipleAsync(Valeant.Sp.UprsWeb.NavisionCarListServiceReference.ReadMultiple request) {
            return base.Channel.ReadMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<Valeant.Sp.UprsWeb.NavisionCarListServiceReference.ReadMultiple_Result> ReadMultipleAsync(Valeant.Sp.UprsWeb.NavisionCarListServiceReference.GetCarList_Filter[] filter, string bookmarkKey, int setSize) {
            Valeant.Sp.UprsWeb.NavisionCarListServiceReference.ReadMultiple inValue = new Valeant.Sp.UprsWeb.NavisionCarListServiceReference.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            return ((Valeant.Sp.UprsWeb.NavisionCarListServiceReference.GetCarList_Port)(this)).ReadMultipleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Valeant.Sp.UprsWeb.NavisionCarListServiceReference.IsUpdated_Result Valeant.Sp.UprsWeb.NavisionCarListServiceReference.GetCarList_Port.IsUpdated(Valeant.Sp.UprsWeb.NavisionCarListServiceReference.IsUpdated request) {
            return base.Channel.IsUpdated(request);
        }
        
        public bool IsUpdated(string Key) {
            Valeant.Sp.UprsWeb.NavisionCarListServiceReference.IsUpdated inValue = new Valeant.Sp.UprsWeb.NavisionCarListServiceReference.IsUpdated();
            inValue.Key = Key;
            Valeant.Sp.UprsWeb.NavisionCarListServiceReference.IsUpdated_Result retVal = ((Valeant.Sp.UprsWeb.NavisionCarListServiceReference.GetCarList_Port)(this)).IsUpdated(inValue);
            return retVal.IsUpdated_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Valeant.Sp.UprsWeb.NavisionCarListServiceReference.IsUpdated_Result> Valeant.Sp.UprsWeb.NavisionCarListServiceReference.GetCarList_Port.IsUpdatedAsync(Valeant.Sp.UprsWeb.NavisionCarListServiceReference.IsUpdated request) {
            return base.Channel.IsUpdatedAsync(request);
        }
        
        public System.Threading.Tasks.Task<Valeant.Sp.UprsWeb.NavisionCarListServiceReference.IsUpdated_Result> IsUpdatedAsync(string Key) {
            Valeant.Sp.UprsWeb.NavisionCarListServiceReference.IsUpdated inValue = new Valeant.Sp.UprsWeb.NavisionCarListServiceReference.IsUpdated();
            inValue.Key = Key;
            return ((Valeant.Sp.UprsWeb.NavisionCarListServiceReference.GetCarList_Port)(this)).IsUpdatedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Valeant.Sp.UprsWeb.NavisionCarListServiceReference.GetRecIdFromKey_Result Valeant.Sp.UprsWeb.NavisionCarListServiceReference.GetCarList_Port.GetRecIdFromKey(Valeant.Sp.UprsWeb.NavisionCarListServiceReference.GetRecIdFromKey request) {
            return base.Channel.GetRecIdFromKey(request);
        }
        
        public string GetRecIdFromKey(string Key) {
            Valeant.Sp.UprsWeb.NavisionCarListServiceReference.GetRecIdFromKey inValue = new Valeant.Sp.UprsWeb.NavisionCarListServiceReference.GetRecIdFromKey();
            inValue.Key = Key;
            Valeant.Sp.UprsWeb.NavisionCarListServiceReference.GetRecIdFromKey_Result retVal = ((Valeant.Sp.UprsWeb.NavisionCarListServiceReference.GetCarList_Port)(this)).GetRecIdFromKey(inValue);
            return retVal.GetRecIdFromKey_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Valeant.Sp.UprsWeb.NavisionCarListServiceReference.GetRecIdFromKey_Result> Valeant.Sp.UprsWeb.NavisionCarListServiceReference.GetCarList_Port.GetRecIdFromKeyAsync(Valeant.Sp.UprsWeb.NavisionCarListServiceReference.GetRecIdFromKey request) {
            return base.Channel.GetRecIdFromKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<Valeant.Sp.UprsWeb.NavisionCarListServiceReference.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(string Key) {
            Valeant.Sp.UprsWeb.NavisionCarListServiceReference.GetRecIdFromKey inValue = new Valeant.Sp.UprsWeb.NavisionCarListServiceReference.GetRecIdFromKey();
            inValue.Key = Key;
            return ((Valeant.Sp.UprsWeb.NavisionCarListServiceReference.GetCarList_Port)(this)).GetRecIdFromKeyAsync(inValue);
        }
    }
}
