//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valeant.Sp.UprsWeb.NavisionCreateAdvanceStatementServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SPIntegration", ConfigurationName="NavisionCreateAdvanceStatementServiceReference.SPIntegration_Binding")]
    public interface SPIntegration_Binding {
        
        // CODEGEN: Generating message contract since the wrapper name (CreateAdvanceStatementHeader_Result) of message CreateAdvanceStatementHeaderResponse does not match the default value (CreateAdvanceStatementHeader)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/SPIntegration:CreateAdvanceStatementHeade" +
            "r", ReplyAction="*")]
        Valeant.Sp.UprsWeb.NavisionCreateAdvanceStatementServiceReference.CreateAdvanceStatementHeaderResponse CreateAdvanceStatementHeader(Valeant.Sp.UprsWeb.NavisionCreateAdvanceStatementServiceReference.CreateAdvanceStatementHeaderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/SPIntegration:CreateAdvanceStatementHeade" +
            "r", ReplyAction="*")]
        System.Threading.Tasks.Task<Valeant.Sp.UprsWeb.NavisionCreateAdvanceStatementServiceReference.CreateAdvanceStatementHeaderResponse> CreateAdvanceStatementHeaderAsync(Valeant.Sp.UprsWeb.NavisionCreateAdvanceStatementServiceReference.CreateAdvanceStatementHeaderRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (CreateAdvanceStatementLine_Result) of message CreateAdvanceStatementLineResponse does not match the default value (CreateAdvanceStatementLine)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/SPIntegration:CreateAdvanceStatementLine", ReplyAction="*")]
        Valeant.Sp.UprsWeb.NavisionCreateAdvanceStatementServiceReference.CreateAdvanceStatementLineResponse CreateAdvanceStatementLine(Valeant.Sp.UprsWeb.NavisionCreateAdvanceStatementServiceReference.CreateAdvanceStatementLineRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/SPIntegration:CreateAdvanceStatementLine", ReplyAction="*")]
        System.Threading.Tasks.Task<Valeant.Sp.UprsWeb.NavisionCreateAdvanceStatementServiceReference.CreateAdvanceStatementLineResponse> CreateAdvanceStatementLineAsync(Valeant.Sp.UprsWeb.NavisionCreateAdvanceStatementServiceReference.CreateAdvanceStatementLineRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateAdvanceStatementHeader", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/SPIntegration", IsWrapped=true)]
    public partial class CreateAdvanceStatementHeaderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SPIntegration", Order=0)]
        public string employeeNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SPIntegration", Order=1)]
        public string advancePurpose;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SPIntegration", Order=2)]
        public string postingDescription;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SPIntegration", Order=3)]
        public string postingDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SPIntegration", Order=4)]
        public string purchaserCode;
        
        public CreateAdvanceStatementHeaderRequest() {
        }
        
        public CreateAdvanceStatementHeaderRequest(string employeeNo, string advancePurpose, string postingDescription, string postingDate, string purchaserCode) {
            this.employeeNo = employeeNo;
            this.advancePurpose = advancePurpose;
            this.postingDescription = postingDescription;
            this.postingDate = postingDate;
            this.purchaserCode = purchaserCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateAdvanceStatementHeader_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/SPIntegration", IsWrapped=true)]
    public partial class CreateAdvanceStatementHeaderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SPIntegration", Order=0)]
        public string return_value;
        
        public CreateAdvanceStatementHeaderResponse() {
        }
        
        public CreateAdvanceStatementHeaderResponse(string return_value) {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateAdvanceStatementLine", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/SPIntegration", IsWrapped=true)]
    public partial class CreateAdvanceStatementLineRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SPIntegration", Order=0)]
        public string advStNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SPIntegration", Order=1)]
        public string gLAccountNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SPIntegration", Order=2)]
        public string vendorPostingGroup;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SPIntegration", Order=3)]
        public string descriptionTxt;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SPIntegration", Order=4)]
        public decimal amountInclVAT;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SPIntegration", Order=5)]
        public string purchDocNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SPIntegration", Order=6)]
        public string purchDocDate;
        
        public CreateAdvanceStatementLineRequest() {
        }
        
        public CreateAdvanceStatementLineRequest(string advStNo, string gLAccountNo, string vendorPostingGroup, string descriptionTxt, decimal amountInclVAT, string purchDocNo, string purchDocDate) {
            this.advStNo = advStNo;
            this.gLAccountNo = gLAccountNo;
            this.vendorPostingGroup = vendorPostingGroup;
            this.descriptionTxt = descriptionTxt;
            this.amountInclVAT = amountInclVAT;
            this.purchDocNo = purchDocNo;
            this.purchDocDate = purchDocDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateAdvanceStatementLine_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/SPIntegration", IsWrapped=true)]
    public partial class CreateAdvanceStatementLineResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SPIntegration", Order=0)]
        public int return_value;
        
        public CreateAdvanceStatementLineResponse() {
        }
        
        public CreateAdvanceStatementLineResponse(int return_value) {
            this.return_value = return_value;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SPIntegration_BindingChannel : Valeant.Sp.UprsWeb.NavisionCreateAdvanceStatementServiceReference.SPIntegration_Binding, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SPIntegration_BindingClient : System.ServiceModel.ClientBase<Valeant.Sp.UprsWeb.NavisionCreateAdvanceStatementServiceReference.SPIntegration_Binding>, Valeant.Sp.UprsWeb.NavisionCreateAdvanceStatementServiceReference.SPIntegration_Binding {
        
        public SPIntegration_BindingClient() {
        }
        
        public SPIntegration_BindingClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SPIntegration_BindingClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SPIntegration_BindingClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SPIntegration_BindingClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Valeant.Sp.UprsWeb.NavisionCreateAdvanceStatementServiceReference.CreateAdvanceStatementHeaderResponse Valeant.Sp.UprsWeb.NavisionCreateAdvanceStatementServiceReference.SPIntegration_Binding.CreateAdvanceStatementHeader(Valeant.Sp.UprsWeb.NavisionCreateAdvanceStatementServiceReference.CreateAdvanceStatementHeaderRequest request) {
            return base.Channel.CreateAdvanceStatementHeader(request);
        }
        
        public string CreateAdvanceStatementHeader(string employeeNo, string advancePurpose, string postingDescription, string postingDate, string purchaserCode) {
            Valeant.Sp.UprsWeb.NavisionCreateAdvanceStatementServiceReference.CreateAdvanceStatementHeaderRequest inValue = new Valeant.Sp.UprsWeb.NavisionCreateAdvanceStatementServiceReference.CreateAdvanceStatementHeaderRequest();
            inValue.employeeNo = employeeNo;
            inValue.advancePurpose = advancePurpose;
            inValue.postingDescription = postingDescription;
            inValue.postingDate = postingDate;
            inValue.purchaserCode = purchaserCode;
            Valeant.Sp.UprsWeb.NavisionCreateAdvanceStatementServiceReference.CreateAdvanceStatementHeaderResponse retVal = ((Valeant.Sp.UprsWeb.NavisionCreateAdvanceStatementServiceReference.SPIntegration_Binding)(this)).CreateAdvanceStatementHeader(inValue);
            return retVal.return_value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Valeant.Sp.UprsWeb.NavisionCreateAdvanceStatementServiceReference.CreateAdvanceStatementHeaderResponse> Valeant.Sp.UprsWeb.NavisionCreateAdvanceStatementServiceReference.SPIntegration_Binding.CreateAdvanceStatementHeaderAsync(Valeant.Sp.UprsWeb.NavisionCreateAdvanceStatementServiceReference.CreateAdvanceStatementHeaderRequest request) {
            return base.Channel.CreateAdvanceStatementHeaderAsync(request);
        }
        
        public System.Threading.Tasks.Task<Valeant.Sp.UprsWeb.NavisionCreateAdvanceStatementServiceReference.CreateAdvanceStatementHeaderResponse> CreateAdvanceStatementHeaderAsync(string employeeNo, string advancePurpose, string postingDescription, string postingDate, string purchaserCode) {
            Valeant.Sp.UprsWeb.NavisionCreateAdvanceStatementServiceReference.CreateAdvanceStatementHeaderRequest inValue = new Valeant.Sp.UprsWeb.NavisionCreateAdvanceStatementServiceReference.CreateAdvanceStatementHeaderRequest();
            inValue.employeeNo = employeeNo;
            inValue.advancePurpose = advancePurpose;
            inValue.postingDescription = postingDescription;
            inValue.postingDate = postingDate;
            inValue.purchaserCode = purchaserCode;
            return ((Valeant.Sp.UprsWeb.NavisionCreateAdvanceStatementServiceReference.SPIntegration_Binding)(this)).CreateAdvanceStatementHeaderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Valeant.Sp.UprsWeb.NavisionCreateAdvanceStatementServiceReference.CreateAdvanceStatementLineResponse Valeant.Sp.UprsWeb.NavisionCreateAdvanceStatementServiceReference.SPIntegration_Binding.CreateAdvanceStatementLine(Valeant.Sp.UprsWeb.NavisionCreateAdvanceStatementServiceReference.CreateAdvanceStatementLineRequest request) {
            return base.Channel.CreateAdvanceStatementLine(request);
        }
        
        public int CreateAdvanceStatementLine(string advStNo, string gLAccountNo, string vendorPostingGroup, string descriptionTxt, decimal amountInclVAT, string purchDocNo, string purchDocDate) {
            Valeant.Sp.UprsWeb.NavisionCreateAdvanceStatementServiceReference.CreateAdvanceStatementLineRequest inValue = new Valeant.Sp.UprsWeb.NavisionCreateAdvanceStatementServiceReference.CreateAdvanceStatementLineRequest();
            inValue.advStNo = advStNo;
            inValue.gLAccountNo = gLAccountNo;
            inValue.vendorPostingGroup = vendorPostingGroup;
            inValue.descriptionTxt = descriptionTxt;
            inValue.amountInclVAT = amountInclVAT;
            inValue.purchDocNo = purchDocNo;
            inValue.purchDocDate = purchDocDate;
            Valeant.Sp.UprsWeb.NavisionCreateAdvanceStatementServiceReference.CreateAdvanceStatementLineResponse retVal = ((Valeant.Sp.UprsWeb.NavisionCreateAdvanceStatementServiceReference.SPIntegration_Binding)(this)).CreateAdvanceStatementLine(inValue);
            return retVal.return_value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Valeant.Sp.UprsWeb.NavisionCreateAdvanceStatementServiceReference.CreateAdvanceStatementLineResponse> Valeant.Sp.UprsWeb.NavisionCreateAdvanceStatementServiceReference.SPIntegration_Binding.CreateAdvanceStatementLineAsync(Valeant.Sp.UprsWeb.NavisionCreateAdvanceStatementServiceReference.CreateAdvanceStatementLineRequest request) {
            return base.Channel.CreateAdvanceStatementLineAsync(request);
        }
        
        public System.Threading.Tasks.Task<Valeant.Sp.UprsWeb.NavisionCreateAdvanceStatementServiceReference.CreateAdvanceStatementLineResponse> CreateAdvanceStatementLineAsync(string advStNo, string gLAccountNo, string vendorPostingGroup, string descriptionTxt, decimal amountInclVAT, string purchDocNo, string purchDocDate) {
            Valeant.Sp.UprsWeb.NavisionCreateAdvanceStatementServiceReference.CreateAdvanceStatementLineRequest inValue = new Valeant.Sp.UprsWeb.NavisionCreateAdvanceStatementServiceReference.CreateAdvanceStatementLineRequest();
            inValue.advStNo = advStNo;
            inValue.gLAccountNo = gLAccountNo;
            inValue.vendorPostingGroup = vendorPostingGroup;
            inValue.descriptionTxt = descriptionTxt;
            inValue.amountInclVAT = amountInclVAT;
            inValue.purchDocNo = purchDocNo;
            inValue.purchDocDate = purchDocDate;
            return ((Valeant.Sp.UprsWeb.NavisionCreateAdvanceStatementServiceReference.SPIntegration_Binding)(this)).CreateAdvanceStatementLineAsync(inValue);
        }
    }
}
